classes = {
    1: 'ENGL202C 103'
}

classLocation = {
    1: '/media/b/Disk of Holding/School/Classes/Grades/Summer 2021/ENGL 202C 103/'
}

assignments = {
    1: 'Rhetorical Analysis',
    2: 'Job Application Package',
    3: 'Technical Definition and Description',
    4: 'Instruction Set',
    5: 'E-Portfolio'
}

assignmentIntros = {
    'Rhetorical Analysis' : """Rhetorical Analysis: This paper is intended to introduce you to several concepts pertinent to the course, including audience, purpose, design, user accessibility, etc., but the primary concept is that of functionality. Ultimately, your paper should be answering one (well, okay two) questions: does this document work? and importantly, WHY or WHY NOT? Your paper should not simply be a summary of what the document is (though that will inevitably find its way into the paper), but instead should address specific parts of your chosen document and discuss why you feel they are effective or not at reaching the audience and solving the problem.""",
    'Job Application Package' : """Job Application Package: This project is intended to accomplish a few things at once, but our primary goal is to gain a firmer understanding of how each tech document is tailored towards a specific audience. Resumes and cover letters are great examples of documents that often become generic 'forms' that are shipped to any promising employer, but in doing so, they miss the point. An effective act of commnuication considers the audience, what they want, and what their expectations are, and then delivers. We are also thinking about design and organization here. Do the choices that you make here make sense? Did you choose them with the audience in mind? Are they easy to read and navigate? And finally, we're also looking at grammar and spelling. It might seem asinine, but tech documents need to be polished.""",
    'Technical Definition and Description' : """Technical Description: This document represents a skillset that you will doubtless be using eventually at your place of employment by requiring you to think about how best to convey important information about a set process or product to a fellow employee, a customer, or even a potential investor. We are shooting for a description that accomplishes a few things: it needs to be composed with a specific, target audience in mind; it should employ an intuitive organizational/navigational system; it should make effective use of visual aids; and finally, it should be composed carefully both mechanically and thoroughly. Are all the steps here that need to be here? Are the appropriate jargon words chosen and highlighted? Does the document successfully employ APA or some other style guide? """,
    'Instruction Set' : """Instruction Set: The instruction set is one of the most ubiquitous forms of technical communication. We run into these constantly in every day life in the form of appliance manuals, repair manuals, recipes, etc. They tell the reader how to DO something. For our purposes, there are a lot of elements that come together for instruction sets that we've already talked about in previous assignments, so for this one we're focusing largely on the elements of design from our book: contrast, alignment, repetition, and proximity. In short, is the document designed so that it is usable? Can I easily follow the steps you've laid out to accomplish the task that you've designated? Are they clear, easy to follow, and written with the imperative (commanding) voice? Successfully composing an instruction set is a skill that you'll likely need at your job, whether it's composing an extensive manual or a quick memo that tells employees how to log into the company system.""",
    'E-Portfolio' : """E-Portfolio: The e-portfolio is an opportunity for you to create a digital space for you as a professional; you are deciding how you want other professionals in your field or potential employers to view you. For the purposes of this course, we're looking for you to demonstrate a few key ideas here: professionalism, of course, but also we want you to think about what changes when we go digital. We're looking for basic design principles, including contrast, alignment and proximity, and we're also considering navigation. Is the page simple and easy to get around? Do you have the necessary parts, like the bio and headshot, a suitable homepage, and a collection of your 'stuff' you want to show off in your portfolio? Is everything presented professionally? In short, is the site well-made and clearly depict you in a professional light?"""
}

assignmentComments = {
    'Rhetorical Analysis': {
       'Audience': {
           1: """Alright, so you've identified a pretty good audience here. It's not just "the people reading this", but an audience who has a goal and comes to the document with some level of understanding.""" ,
           2: """So your audience here works okay. I think there's a little more room for speficity, though. What kind of person would want to read this? What information would they need? What would they already know? Did the designers of the document take this information into account? What makes you think so? """,
           3: """You want to identify who you think the target audience is as concretely as possible. What you have here is not specific enough. Who was this document designed for? And don't say, "Anyone who reads it." That's never the correct answer. What kind of person would want to read this? What information would they need? What would they already know? Did the designers of your document take this into account? What makes you think so?"""
       },
       'Purpose (Problem  (3 = Not Present))': {
           1: """You were able to identify the purpose of the document, which is always 'to solve a problem' of some kind. You gave some specific details about what was the issue and how the reader could solve the problem. Great! It's not just 'the reader could use this to fix their car' or something, but rather, 'the reader would use this when changing the oil in the car. That level of specificity is what we'll be looking for in all our projects in this class, and indeed in any technical writing document that you create, independent of this class.""",
           2: """Okay, you've listed a purpose here, but it's a little more vague than what we're shooting for. A tech document exists to solve a particular problem. An Ikea instruction manual tells you how to build a table. A coffee maker instruction manual tells you how to get it working. What does your document do? What is the specific reason a person would read this? It's not just 'the reader could use this to fix their car' or something, but rather, 'the reader would use this when changing the oil in the car. That level of specificity is what we'll be looking for in all our projects in this class, and indeed in any technical writing document that you create, independent of this class.""",
           3: """One of the required components of the paper is missing, specifically that of the document's purpose. A tech document exists to solve a particular problem. An Ikea instruction manual tells you how to build a table. A coffee maker instruction manual tells you how to get it working. What does your document do? What is the specific reason a person would read this? It's not just 'the reader could use this to fix their car' or something, but rather, 'the reader would use this when changing the oil in the car. That level of specificity is what we'll be looking for in all our projects in this class, and indeed in any technical writing document that you create, independent of this class. Unfortunately, your analysis of this is missing."""
       },
       'Design (3 = Not Present)': {
           1: """You have some good discussion here about considerations of design as well. At this stage of the class, we don't need a super in-depth analysis of things like typography, white space, organization, and color, and what you have here is perfectly sufficient. You engage with some design choices and you consider how the help (or hinder) the reader's ability to navigate the document. Nicely done.""",
           2: """You grappled with some of the ideas of design here, which is good. At this stage of the class, we don't need a super in-depth analysis of things like typography, white space, organization, and color, but you do want to be thinking about literally, physically how does the document look? Is it organized in a way that makes reading it easy? Or is it cluttered and confusing?""",
           3: """We are missing some of your thoughts about design here. At this stage of the class, we don't need a super in-depth analysis of things like typography, white space, organization, and color, but you do want to be thinking about literally, physically how does the document look? Is it organized in a way that makes reading it easy? Or is it cluttered and confusing?"""
       },
       'Images (3 = Not Present)' : {
           1: """Regarding the images used in the document, you have a pretty solid discussion going on here. Images and graphs are one of the topics that we'll spend a good bit of time on this semester because they are integral to nearly all forms of technical communication. The fact that you are already thinking about them and their usefulness to the understanding of the document (and the problem it's trying to solve) is a good sign!""",
           2: """Regarding the images used in the document, you discuss them briefly, but I think there's a little more room for deeper analysis. Consider the purpose of the document, i.e., what problem is this trying to solve, and then consider whether or not you think the images included are useful in achieving that goal. Images and graphs are one of the topics that we'll spend a good bit of time on this semester because they are integral to nearly all forms of technical communication.""",
           3: """Regarding the images used in the document, you basically ignore them. Which is a shame, because images are super important to tech documents!Consider the purpose of the document, i.e., what problem is this trying to solve, and then consider whether or not you think the images included are useful in achieving that goal. Images and graphs are one of the topics that we'll spend a good bit of time on this semester because they are integral to nearly all forms of technical communication."""
       },
       'Organizational Goals and Culture' : {
           1: """One of the more slippery ideas of tech writing is that the documents often are not the creation of any singular person or their personal thoughts, but rather are created by an organization or business with a set of criteria that are pre-established. In a lot of ways, tech writers are workign from a cookie-cutter mold. An employee of Facebook, for example, isn't going to talk about how social media is bad for teen mental health in an official Facebook document, because the organizaion has laid out rules preventing that. With this in mind, you have a decent analysis of the organizational culture here that considers what decisions were made for the writer, which is good. This will be especially important on the next assignment where you have to carefully analyze the culture of a business you are interested in applying for.""",
           2: """One of the more slippery ideas of tech writing is that the documents often are not the creation of any singular person or their personal thoughts, but rather are created by an organization or business with a set of criteria that are pre-established. In a lot of ways, tech writers are workign from a cookie-cutter mold. An employee of Facebook, for example, isn't going to talk about how social media is bad for teen mental health in an official Facebook document, because the organizaion has laid out rules preventing that. With this in mind, you have an okay analysis of the organizational culture here. Consider what decisions were made for the writer, and why the organization would employ these constraints. This will be especially important on the next assignment where you have to carefully analyze the culture of a business you are interested in applying for.""",
           3: """One of the more slippery ideas of tech writing is that the documents often are not the creation of any singular person or their personal thoughts, but rather are created by an organization or business with a set of criteria that are pre-established. In a lot of ways, tech writers are workign from a cookie-cutter mold. An employee of Facebook, for example, isn't going to talk about how social media is bad for teen mental health in an official Facebook document, because the organizaion has laid out rules preventing that. With this in mind, you are missig your analysis of the organizational culture. Consider what decisions were made for the writer, and why the organization would employ these constraints. This will be especially important on the next assignment where you have to carefully analyze the culture of a business you are interested in applying for."""
       }
    },
    #############################################################################################################################################
    'Job Application Package': {
        'Resume Design and Organization' : {
            1:"""So your resumes look pretty clean and polished. They are visually easy to navigate, and the organization makes sense. When we're talking organizaion we're thinking about the order of the information. Is the important information about who you are and what your skills are located at the top of the document, with less important information located further down? Do you have information here that is 'fluff' or is everything presented relevant to the job at hand? Could an HR manager read this quickly and easily and make a decision about whether you are the correct candidate? I think what you've created here for your resumes works well here. You seem to have embraced the majority of the concepts we are shooting for, and this looks pretty good!""",
            2:"""When we're talking organizaion we're thinking about the order of the information. Is the important information about who you are and what your skills are located at the top of the document, with less important information located further down? Do you have information here that is 'fluff' or is everything presented relevant to the job at hand? Could an HR manager read this quickly and easily and make a decision about whether you are the correct candidate? I think that you do a pretty decent job of this, but there's always some room for improvement. Remember to organize and include information that's only relevant to the job ad that you're posting for (or if you want to make the case for including seemingly irrelevant information, make sure you do so in your cover letter). We want the important information about who you are and why you, specifically, are qualified for this job to come first and foremeost, to be easy to find, and to visually pop with your design. So I think you're mostly there, but there's a few things here that could be shifted around to make this even more targeted for your chosen job.""",
            3:"""When we're talking organizaion we're thinking about the order of the information. Is the important information about who you are and what your skills are located at the top of the document, with less important information located further down? Do you have information here that is 'fluff' or is everything presented relevant to the job at hand? Could an HR manager read this quickly and easily and make a decision about whether you are the correct candidate? I think we've definitely got some room for improvement here. There seems to be little rhyme or reason to how your information is organized and presented aside from a generic understanding of 'Here's what I've done.' Try to think a little more critically about what the specific job is asking for and how you can create a resume that speaks to the needs of the position and the company you've researched. Make sure that you chop out any fluff like irrelevant jobs and present a polished, carefully constructed resume."""
        },
        'Cover Letter Design and Organization' : {
            1:"""The cover letters are fairly similar to the resume in terms of what we're looking for. We want the important, relevant information that pertains to the specific job that we're applying for to appear. We're looking for the visual format of a cover letter (four paragraphs-ish), and are closely considering the content that you've included in those midddle paragraphs, which should tightly align with the job description and the culture of the company. And I feel like you've nailed this pretty well. The information you've included here isn't extraneous fluff, but rather it is carefully targeted to condsider what the job needs and wants and even what the company is interested in. This is great. Since you've only got two paragraphs to really work with here and tell your story, it's important that you are hyper focused, and, again, I think you demonstrate this with aplomb.""",
            2:"""The cover letters are fairly similar to the resume in terms of what we're looking for. We want the important, relevant information that pertains to the specific job that we're applying for to appear. We're looking for the visual format of a cover letter (four paragraphs-ish), and are closely considering the content that you've included in those midddle paragraphs, which should tightly align with the job description and the culture of the company. You've largely done this. I think that some of your writing here veers a little towards vagueness, i.e., you could say the same thing regardless of the job that you're applying for. By being more specific in in your information and including key words and ideas that are found in the job description, this could look a little less like a generic cover letter, and more like one that is carefully tailored for the expectations of the job and the company. Which is not to say that you don't do this at all - but there's some spots here where we could dive a little deeper still and create a tight, targeted letter.""",
            3:"""The cover letters are fairly similar to the resume in terms of what we're looking for. We want the important, relevant information that pertains to the specific job that we're applying for to appear. We're looking for the visual format of a cover letter (four paragraphs-ish), and are closely considering the content that you've included in those midddle paragraphs, which should tightly align with the job description and the culture of the company. I feel like these letters are treading a little too closely to the generic resume that you could use for any job. Don't get me wrong - sometimes it's good and useful to have a generic cover letter that you can just toss at anyone quickly, but for the purposes of this assignment, we were really wanting you to think about and target that audience and the specific job. Consider a little more carefully what you are including and why you are including it. Compose your letter with the ad sitting right next to you and figure out which key words and concepts need to be demonstrated in the letter. Similarly, check out the company website and see what they value in a candidate and make sure that you get some of that in your cover letters, too!"""
        },
        'Memo' : {
            1:"""The primary goal of the memo letter is to give you an opportunity to have a direct line of communication to me and explain why you made the choices that you made. If you made unusual choices in your packet, e.g., your resumes are extremely similar or you chose to do a nontraditional resume, I want to know why. And yeah, you do everything we're looking for here. You tell me what's up and explain thoroughly your rationale. Looks good.""",
            2:"""The primary goal of the memo letter is to give you an opportunity to have a direct line of communication to me and explain why you made the choices that you made. If you made unusual choices in your packet, e.g., your resumes are extremely similar or you chose to do a nontraditional resume, I want to know why. And yeah, this looks pretty good. There were a few things that caught my eye that I think could have been explained a little more in detail (I'll list them below), but overall the letter does what it's supposed to do and largely explains your rationale and decision making.""",
            3:"""The primary goal of the memo letter is to give you an opportunity to have a direct line of communication to me and explain why you made the choices that you made. If you made unusual choices in your packet, e.g., your resumes are extremely similar or you chose to do a nontraditional resume, I want to know why. I feel like we're missing a few pieces of the puzzle here with your memo. I have some questions about your decision-making that don't get answered, and importantly, we're missing some of the required components. We need a thorough description of the job and the company both, your rationale for your choices, and an explanantion of what you did to differentiate the two jobs, and I'm not getting all of that here."""
        },
        'Grammar and Mechanics' : {
            1:"""Typically speaking, I don't care all that much as a teacher about correcting grammar and mechanical mistakes. I feel like these sorts of errors can be corrected without too much ado, so I don't focus on them. But in the spirit of mirroring the conditions of the job market, for this assignment I am paying attention to them. But that doesn't matter to you, because this looks pretty good and clean. If there are any errors here, I didn't catch them, so good on you.""",
            2:"""Typically speaking, I don't care all that much as a teacher about correcting grammar and mechanical mistakes. I feel like these sorts of errors can be corrected without too much ado, so I don't focus on them. But in the spirit of mirroring the conditions of the job market, for this assignment I am paying attention to them. Your documents looks largely error free, but I did catch a few places where a typo or grammatical mistake slipped through. Don't forget - when you're applying for a job against potentionally hundreds of other candidates, use every advantage you can get. Even boring English grammar.""",
            3:"""Typically speaking, I don't care all that much as a teacher about correcting grammar and mechanical mistakes. I feel like these sorts of errors can be corrected without too much ado, so I don't focus on them. But in the spirit of mirroring the conditions of the job market, for this assignment I am paying attention to them. And yeah, it's a place where you could use a little work. The grammar here is a little wonky and could use some editing. If you're not particularly great with English grammar (I don't blame you), then consider using the tutoring services on campus or even find a friend to edit your paper for you before you turn it in to catch these errors."""
        }

    },
    #############################################################################################################################################
    #Tech Description
    'Technical Definition and Description': {
        'Audience and Purpose' : {
            1: """Alright, so one of the principle ideas we're dealing with here is thinking about the audience and what they already know versus what they need to know. Assumptions need to be made when it comes to jargon or concepts that are outside the purview of the lay reader about whether or not a concept needs to be explained in further detail or can be safely skipped over because it can be assumed that your reader is already familiar with the idea. I think you're doing exactly that here. Your identified audience makes sense and you don't simply state who they are, but also think a little more in depth about who they are and what you expect them to already know (or not). The vocab words and ideas that you have gone into detail explaining make sense for your chosen audience, and I don't think there's anything here that seems overly pedantic. Looks good.""",
            2: """Alright, so one of the principle ideas we're dealing with here is thinking about the audience and what they already know versus what they need to know. Assumptions need to be made when it comes to jargon or concepts that are outside the purview of the lay reader about whether or not a concept needs to be explained in further detail or can be safely skipped over because it can be assumed that your reader is already familiar with the idea. You're definitely on the right track here, but you want to be careful about being a little overly vague in that audience. We want specifics and assumptions about those specifics. 'An aerospace college student,' for example, is a little vague. Something like 'A college junior in aerospace engineering with a background in aerodynamics' is significantly more precise and better indicates the choices that need to be made when you are selecting your vocab/jargon or extended definitions that need to be explained. Try to bring this in a little bit more and think about who this document is created for with a little more precision.""",
            3: """Alright, so one of the principle ideas we're dealing with here is thinking about the audience and what they already know versus what they need to know. Assumptions need to be made when it comes to jargon or concepts that are outside the purview of the lay reader about whether or not a concept needs to be explained in further detail or can be safely skipped over because it can be assumed that your reader is already familiar with the idea. And I think that you're target audience here is really just a bit too vague to meaningfully do this. We really need to zoom in on who you think will actually read this. The answer to "who is the audience?" is never just "the reader." We need to know what kind of reader, what kind of knowledge do they come to the table with, or else we can't meaningfully make decisions about what jargon words or ideas need more explication. Without a precise audience, we're just throwing darts as to what information needs further explanation. Try to bring into focus a little more clealry who you are composing this document for."""
        },
        'Organization' : {
            1: """When composing a 'normal' document (as opposed to a tech document) and we're thinking about organization, we're dealing with literally how the words and ideas are presented in a paper. You're probably familiar with the standard, 5-paragraph essay that they love to teach in high school. While that methodology can work well in much academic writing, tech writing is a bit of a different beast when it comes to organization. Instead, we're heavily focused on usability. Do I understand the thing that you are trying to teach me. As such, we're looking for either a step-by-step organizational model or the description of a product in a 'direction' that makes sense, i.e., top to bottom or simplest to most complex. What you've composed here fits the bill pretty well, I think. There is a clear description that is intuitive to follow. Each section/paragraph is both modular but also makes sense in its postiion in the larger context of your piece. Overall, I think your document both flows and is chunky (a good thing!), which is somewhat the paradox of tech writing. Each section should stand on its own, but also make sense in the larger context. And yours does, so that's great!""",
            2: """When composing a 'normal' document (as opposed to a tech document) and we're thinking about organization, we're dealing with literally how the words and ideas are presented in a paper. You're probably familiar with the standard, 5-paragraph essay that they love to teach in high school. While that methodology can work well in much academic writing, tech writing is a bit of a different beast when it comes to organization. Instead, we're heavily focused on usability. Do I understand the thing that you are trying to teach me. As such, we're looking for either a step-by-step organizational model or the description of a product in a 'direction' that makes sense, i.e., top to bottom or simplest to most complex. I think that what we have in this document is working reasonably well. I do think there is some room to think about the modular but still flows paradox of technical writing, i.e., each section should stand on its own but still makes sense in its position within the document. Consider your organizaitional model, e.g., chronological or directional, and look at each of your paragraphs. Are you consistently following that model? Or are some paragraphs/topics discussed a little haphazardly?""",
            3: """When composing a 'normal' document (as opposed to a tech document) and we're thinking about organization, we're dealing with literally how the words and ideas are presented in a paper. You're probably familiar with the standard, 5-paragraph essay that they love to teach in high school. While that methodology can work well in much academic writing, tech writing is a bit of a different beast when it comes to organization. Instead, we're heavily focused on usability. Do I understand the thing that you are trying to teach me. As such, we're looking for either a step-by-step organizational model or the description of a product in a 'direction' that makes sense, i.e., top to bottom or simplest to most complex. And I think this is a spot we can improve on a bit. What you have here is a lot of good information, but it doesn't seem to follow a good rhyme or reason to why some paragraphs come before or after others. Definitely look at the organizational models suggested in the assigment sheet/book and think about how you could organize this so it is both modular and (paradoxically) fluid. The common choices of organization are either chronological, i.e., step-by-step, or directional, i.e., top to bottom. But you choose the one that makes sense for your particular document."""
        },
        'Visual Aids' : {
            1: """Images are of course a huge part of this assignment, and the employment of them is super important to grasp. Tech writing has A LOT of images, generally speaking, and you need to make sure that you understand how to employ them. For this assignment, we're looking for the three step shuffle: 1) The images need a title and label, e.g., Figure 1. A dog chewing on a bone. 2) The images need proper citation (unless the image is self-created). 3) The image should be discussed in the actual text of the document itself. And it looks like you've managed to do this for all of your images, figures, and whatnot. Looks on point. I don't have much more to add here. Do exactly what you just did on the rest of the assignments and in your future tech writing and you'll be good to go!""",
            2: """Images are of course a huge part of this assignment, and the employment of them is super important to grasp. Tech writing has A LOT of images, generally speaking, and you need to make sure that you understand how to employ them. For this assignment, we're looking for the three step shuffle: 1) The images need a title and label, e.g., Figure 1. A dog chewing on a bone. 2) The images need proper citation (unless the image is self-created). 3) The image should be discussed in the actual text of the document itself. Most of what we're looking for is here, but you do have a few spots where we might be able to clean this up. Double check all your images and make sure your're doing point 1, 2 and 3 for each and every image. Additionally, also consider how useful the images are. If they are there just to look nice, they should go. But if they help to explain a complicated concept, then they should stay.""",
            3: """Images are of course a huge part of this assignment, and the employment of them is super important to grasp. Tech writing has A LOT of images, generally speaking, and you need to make sure that you understand how to employ them. For this assignment, we're looking for the three step shuffle: 1) The images need a title and label, e.g., Figure 1. A dog chewing on a bone. 2) The images need proper citation (unless the image is self-created). 3) The image should be discussed in the actual text of the document itself. Unfortunately, we're missing many of these parts. Go back and check out all your images again. Verify that they accomplish all three of these points. If they don't, you'll want to go back and add all that information. The successful use of images is integral to tech writing, so you want to make sure you get this down pat: Label, cite, discuss. Every image, every time."""
        },
        'Thoroughness' : {
            1: """Thoroughness as a concept is a little harder to pinpoint than whether or not you successfully employed the three step shuffle for your images. Basically here we're thinking about whether or not you've provided enough information for your target audience to fully understand the process or product you are trying to describe. Obviously there are some objective parts here, e.g., you didn't mention that a car even has an engine when you described it's ignition system, but largely this criterion is more subjective and BASED ON THE AUDIENCE you chose. You could probably leave out the part about an engine being in a car if you're talking to another mechanic, but you should absolutely mention it if you're talking to a five year-old. So basically the question is: did you provide enough information to fully educate your reader about your topic? Or is there some important information that you skipped over? I'm going with yes, I think this is thorough and sufficient enough for that audience to understand. All of the parts and processes seem to be here and are explained reasonably well. It's worth noting that I'm not expert in much of anything but English writing, so you COULD be missing something. But I think not. Looks good to me.""",
            2: """Thoroughness as a concept is a little harder to pinpoint than whether or not you successfully employed the three step shuffle for your images. Basically here we're thinking about whether or not you've provided enough information for your target audience to fully understand the process or product you are trying to describe. Obviously there are some objective parts here, e.g., you didn't mention that a car even has an engine when you described it's ignition system, but largely this criterion is more subjective and BASED ON THE AUDIENCE you chose. You could probably leave out the part about an engine being in a car if you're talking to another mechanic, but you should absolutely mention it if you're talking to a five year-old. So basically the question is: did you provide enough information to fully educate your reader about your topic? Or is there some important information that you skipped over? I think this looks pretty solid, but I do wonder if you're not making some assumptions about what your audience knows already. I think there's a little more room here to spell out some of the features and steps in the process that you are sort of glossing over that, I think, would be benificial to your audience if you spelled them out. If you want to know the specific sections I'm thinking of, we can meet on Zoom, but reread your audience first, look at each of your sections here, and think if there's anything that might be skipped over that COULD be important.""",
            3: """Thoroughness as a concept is a little harder to pinpoint than whether or not you successfully employed the three step shuffle for your images. Basically here we're thinking about whether or not you've provided enough information for your target audience to fully understand the process or product you are trying to describe. Obviously there are some objective parts here, e.g., you didn't mention that a car even has an engine when you described it's ignition system, but largely this criterion is more subjective and BASED ON THE AUDIENCE you chose. You could probably leave out the part about an engine being in a car if you're talking to another mechanic, but you should absolutely mention it if you're talking to a five year-old. So basically the question is: did you provide enough information to fully educate your reader about your topic? Or is there some important information that you skipped over? There's a good bit here that I think is glossed over that could do with a bit (or a lot) more explanation. Remember, the primary goal of tech writing is to get an important bit of information from your brain to the reader's. What might they already know? More importantly, what DON'T they know? There's a lot of the pieces of the puzzle here that I think are missing or are overly simplified. See if you can break down some of these ideas into smaller, more discrete parts."""
        },
        'Style' : {
            1: """Style here is referring to the visual design elements. In short, does it look nice and read well? We're thinking here about headers, typography, colors, white space, bullet points and lists, etc. In short, anything that is not the 'text' per se, but visual elements that help with the flow of the document regardless of the writing itself. If this document was writing ancient Aramaic, I should still be able to pick out the style elements and identify how they are helping (or hindering) your writing. You've got functional headers, the typography makes sense and your vocab words 'pop' and are easy to identify, the lists that you use (even headers are essentially 'lists') make sense and group your ideas together intuitively, and importantly, the document just looks clean and easy to navigate. Spot on.""",
            2: """Style here is referring to the visual design elements. In short, does it look nice and read well? We're thinking here about headers, typography, colors, white space, bullet points and lists, etc. In short, anything that is not the 'text' per se, but visual elements that help with the flow of the document regardless of the writing itself. If this document was writing ancient Aramaic, I should still be able to pick out the style elements and identify how they are helping (or hindering) your writing. This looks pretty good! There's some spots of course where we can consider a little more carefully some of those design choices. Think about how we can make everything 'pop', i.e., catch the reader's eye so that they can quickly browse your document and find the information they are looking for. We also might think about the use of white space or even reconsider some of the typography, e.g., the use of bold, italics, or underlined font. But this is nitpicking to a degree. I think it looks pretty clean and is fairly easy to navigate.""",
            3: """Style here is referring to the visual design elements. In short, does it look nice and read well? We're thinking here about headers, typography, colors, white space, bullet points and lists, etc. In short, anything that is not the 'text' per se, but visual elements that help with the flow of the document regardless of the writing itself. If this document was writing ancient Aramaic, I should still be able to pick out the style elements and identify how they are helping (or hindering) your writing. The style and design here could use a little work. Consider ways to better highlight important information and make it stand out to the reader. We also want to think a little more about that white space. We don't want the document to look overly busy and complicated, sure, but we also don't want it to look empty and barren. We're shooting for that Golilocks space. Think of how you could rearrange the text and images on the page to make the document look a little cleaner and full without being busy."""
        }
    },
    #############################################################################################################################################
    #Instruction Set
    'Instruction Set': {
        'Design: Contrast and Alignment' : {
            1:"""Design is the biggest concept we're thinking about when looking at these instructions sets because it's the big, new idea for the project. Two of the concepts focus on the reader's ability to quickly find information while also indicating the importance of that information. Big, bold, colorful headers are used to emphasize important information while bullets and lists can be used to organize information based upon detail. The more detailed the information, the deeper into a list it might go, e.g., point 1.a. is more detailed than just 1. As for what you've created here, you're using these principles correctly. The colors work - they contrast with and 'pop' against the black text and they allow the reader to quickly navigate your document without necessarily reading all of the points. Any lists or bullet points you have here work well at separating the more intricate information from the broader strokes, and they are used appropriately to break up larger chunks of text. Overall, these two design principles look pretty good!""", 
            2:"""Design is the biggest concept we're thinking about when looking at these instructions sets because it's the big, new idea for the project. Two of the concepts focus on the reader's ability to quickly find information while also indicating the importance of that information. Big, bold, colorful headers are used to emphasize important information while bullets and lists can be used to organize information based upon detail. The more detailed the information, the deeper into a list it might go, e.g., point 1.a. is more detailed than just 1. I think what you've got here works reasonably well. Be mindful of some of the basic rules: break down any longer paragraphs or even lists into smaller sections so as not to overwhelm the reader. Also, don't forget to use those colors and that contrast to signal key, important information. This includes headers, sure, but also consider vocab words, warnings, or tips that might be important for a reader to take special note of.""",
            3:"""Design is the biggest concept we're thinking about when looking at these instructions sets because it's the big, new idea for the project. Two of the concepts focus on the reader's ability to quickly find information while also indicating the importance of that information. Big, bold, colorful headers are used to emphasize important information while bullets and lists can be used to organize information based upon detail. The more detailed the information, the deeper into a list it might go, e.g., point 1.a. is more detailed than just 1. So we've got a little room for work in this department. Be mindful of some of the basic rules: break down any longer paragraphs or even lists into smaller sections so as not to overwhelm the reader. Also, don't forget to use those colors and that contrast to signal key, important information. This includes headers, sure, but also consider vocab words, warnings, or tips that might be important for a reader to take special note of. Try to play with color and lists to really point out those sections and information that is super important for your reader to be aware of."""
        },
        'Design: Repetition and Proximity' : {
            1:"""The second set of concepts we want to focus on with regards to design have to deal with the ease of use. Remember, the big(gest?) idea of tech writing is that a document needs to DO something, and the best way to do that is to create writing/documents that are easy to read, easy to interpret, and have no extraneous information to distract the reader from accomplishing that goal. Repetition here refers to consistency in design elements: are your headers all styled the same? Do you consistently employ the same typography for warnings or tips or vocab words or other important information? In short, can the reader quickly understand what each typographical or design element is intended to do across the document without much effort? Proximity is similarly referring to ease of use. Do images or "extra" bits of information appear where they should, i.e., when they are relevant and can be referenced? Is it obvious which pictures go with which descriptions? Does their physical proximity on the page help the reader's understanding? Or do they need to search for it? And yeah, I think what you've done here works well. You are consistent in your design, the design itself is useful, and the information/images are right where they make sense. The reader doesn't have to flip pages to find a vocab word or scratch their head about what image connects to what writing.""",
            2:"""The second set of concepts we want to focus on with regards to design have to deal with the ease of use. Remember, the big(gest?) idea of tech writing is that a document needs to DO something, and the best way to do that is to create writing/documents that are easy to read, easy to interpret, and have no extraneous information to distract the reader from accomplishing that goal. Repetition here refers to consistency in design elements: are your headers all styled the same? Do you consistently employ the same typography for warnings or tips or vocab words or other important information? In short, can the reader quickly understand what each typographical or design element is intended to do across the document without much effort? Proximity is similarly referring to ease of use. Do images or "extra" bits of information appear where they should, i.e., when they are relevant and can be referenced? Is it obvious which pictures go with which descriptions? Does their physical proximity on the page help the reader's understanding? Or do they need to search for it? Most of the time, this works pretty well for your document. There were a few instances when I thought there was some inconsistency in the design elements or when the pictures confused me for a brief moment (see the note below), but generally speaking, I think you successfully employed this design idea.""",
            3:"""The second set of concepts we want to focus on with regards to design have to deal with the ease of use. Remember, the big(gest?) idea of tech writing is that a document needs to DO something, and the best way to do that is to create writing/documents that are easy to read, easy to interpret, and have no extraneous information to distract the reader from accomplishing that goal. Repetition here refers to consistency in design elements: are your headers all styled the same? Do you consistently employ the same typography for warnings or tips or vocab words or other important information? In short, can the reader quickly understand what each typographical or design element is intended to do across the document without much effort? Proximity is similarly referring to ease of use. Do images or "extra" bits of information appear where they should, i.e., when they are relevant and can be referenced? Is it obvious which pictures go with which descriptions? Does their physical proximity on the page help the reader's understanding? Or do they need to search for it? I do feel like these elements are in need of some love here. The images that are used are either confusingly placed or just confusing in what they are supposed to be doing. Remember, images are to be included only to clarify difficult concepts. You also might want look at your typography and design choices. Make sure everything aligns: same font, same size, same formatting. This will allow the reader to better and more quickly interpret your document."""
        },
        'Audience' : {
            1:"""Sadly, the audience never goes away when thinking about writing and communication generally, and tech writing is not exception. Fortunately, we had a protion of our audience for this project spelled out for us in the assignment sheet: someone who has never completed this task before. But there are different levels of that, certainly. Someone who has never looked in under the hood of a car falls into this category, but so does someone who is a professional mechanic but who has never done X specific task. So we are looking to see what kind of audience you settle upon and whetehr the jargon and assumptions you make align with that audience. You went out of your way to zoom in on a specific subset of that audience and anticipated what sort of person they might be and what they would already know or need to know. Because of that, we can look through your document and see where choices are being made based on those assumtions. Those choices that you make here are, I think, right on point. You choose an appropriate level of vocabulary, you explain anything that they MIGHT know but maybe not, and you don't overexplain when discussing an idea they should already know. Perfect!""",
            2:"""Sadly, the audience never goes away when thinking about writing and communication generally, and tech writing is not exception. Fortunately, we had a protion of our audience for this project spelled out for us in the assignment sheet: someone who has never completed this task before. But there are different levels of that, certainly. Someone who has never looked in under the hood of a car falls into this category, but so does someone who is a professional mechanic but who has never done X specific task. So we are looking to see what kind of audience you settle upon and whetehr the jargon and assumptions you make align with that audience. I think a little more precision here about who you are writing to would be beneficial because it tells us (and me) why you are making certain assumptions about what that audience already knows, what they might know, and what they definitely don't know and need to know. What you have here works decently well, but a better document that is even still more accessible to a reader can be composed with a clearer definition and understanding of who that audience. As is, you wrote for a fairly generalized 'person who doesn't know' and that' totally fine. But we can always do a little better. :)""",
            3:"""Sadly, the audience never goes away when thinking about writing and communication generally, and tech writing is not exception. Fortunately, we had a protion of our audience for this project spelled out for us in the assignment sheet: someone who has never completed this task before. But there are different levels of that, certainly. Someone who has never looked in under the hood of a car falls into this category, but so does someone who is a professional mechanic but who has never done X specific task. So we are looking to see what kind of audience you settle upon and whetehr the jargon and assumptions you make align with that audience. I think the audience gets a little lost here. There is some disconnect between whether you are envisioning this to be useful to a semi-expert or a completely brand new/ignorant reader. Because of that, sometimes you overexplain or underexplain some elements that make the instruction set a little unclear. See if you can't think about who your hypothetical reader might be. Are they someone who is really familiar with the core concepts but simply have never performed this specific task? Or is someone who is utterly new to your field/concept and needs to have a lot of the basics explained to them?"""
        },
        #Usability rank 3 is for summer. Check it out. 
        'Usability' : {
            1:"""Usability is kind of the catch-all category and the most important. Unfortunately, it's also a little subjective so it's hard to pin down. But in short, usability is thinking about whether your instruction set does what it is supposed to do. Can I read it, as your target audience, and complete the task? This is thinking about the thoroughness of the information presented (does it skip key steps or underexplain them?) in conjuction with the three points listed about, thinking about design and the audience. I feel like when we look at your document it passes this litmus test without too much ado. What you've created is easy to navigate, it includes all relevant step and information (I think), and it's composed so that your dedicated audience should be able to complete the task successfully (again, I think - this is a little subjective). When all is said and done, the document succeeeds at the most important level, usability. So hoorah!""",
            2:"""Usability is kind of the catch-all category and the most important. Unfortunately, it's also a little subjective so it's hard to pin down. But in short, usability is thinking about whether your instruction set does what it is supposed to do. Can I read it, as your target audience, and complete the task? This is thinking about the thoroughness of the information presented (does it skip key steps or underexplain them?) in conjuction with the three points listed about, thinking about design and the audience. I think your document, when we put all the pieces together, passes the litmus test. Is it an utterly perfect paper in every way? Eh, maybe not. But if we stand by the tennet that effective tech writing is ultimately defined by it's ability to accomplish a task - apply for a job, describe a product, teach someone how to perform a teask - then I think your paper succeeds on that very important level. So that's great. Take a look at some of your design/audience choices to think about how we can bump this up to the next level, but so far so good!""",
            3:"""Usability is kind of the catch-all category and the most important. Unfortunately, it's also a little subjective so it's hard to pin down. But in short, usability is thinking about whether your instruction set does what it is supposed to do. Can I read it, as your target audience, and complete the task? This is thinking about the thoroughness of the information presented (does it skip key steps or underexplain them?) in conjuction with the three points listed about, thinking about design and the audience. And I think this document has some flaws that make it a little more difficult to navigate than it ideally should. I'm not 100% certain that, based on what you've included here, your target audience could successfully complete the task without either having lots of questions or without a substantial amount of confusion. If you want, we can meet up on Zoom and talk about it, but take note that we're in the crunch time for class. The end is nigh! So if we want to fix this up we should do it sooner rather than later!"""
        }

    },
    #############################################################################################################################################
    #e-Portfolio
    'E-Portfolio': {
        'Audience/Professionalism' : {
            1:"""Of course our biggest concern here lies in the overall presentation of you as a professional and how your audience, i.e., people in your specific field or potential employers, will view you and your web page. Looking at the page broadly, we want to ask if it comes across as professional in all of the elements: design, content, navigation, etc. Is your writing and your information relevant and in line with your potential occupation? And yeah, everything here looks pretty sharp. The information you choose to include is relevant, the writing itself maintains a formal tone, and the design is not overly garish but instead maintains a level of simplicity and elegance. Overall, I think it looks pretty solid.""",
            2:"""Of course our biggest concern here lies in the overall presentation of you as a professional and how your audience, i.e., people in your specific field or potential employers, will view you and your web page. Looking at the page broadly, we want to ask if it comes across as professional in all of the elements: design, content, navigation, etc. Is your writing and your information relevant and in line with your potential occupation? I do think there's a little room for improvement here. Some of the choices you've made don't 100% exude a level of tight professionalism. Remember that audience and what they are going to be interested in and want to see. They want a simple-to-navigate page that looks sharp, they want information about you and your professional interests (and nothing else), and they expect a level of formality here. See if you can't reign in some of your design choices to up your professionalism game to 100%.""",
            3:"""Of course our biggest concern here lies in the overall presentation of you as a professional and how your audience, i.e., people in your specific field or potential employers, will view you and your web page. Looking at the page broadly, we want to ask if it comes across as professional in all of the elements: design, content, navigation, etc. Is your writing and your information relevant and in line with your potential occupation? And this page is not quite hitting the mark here. It's... unprofessional, for lack of a better word. Remember, this is not a Facebook or Instagram page. We want to design a site that only shows off the serious, career-minded side of you. See if you can't make some design choices here that will give the audience what they are looking for: They want a simple-to-navigate page that looks sharp, they want information about you and your professional interests (and nothing else), and they expect a level of formality here."""
        },
        'Complete Content' : {
            1:"""Here we are just looking for the basics: do you have all the parts here that you are supposed to. We need a decent homepage, a biography of yourself, a professional looking photo of yourself, a copy of your resume, and a collection of your work/research/projects,etc. And yep. You've got everything you need. Looks good.""",
            2:"""Here we are just looking for the basics: do you have all the parts here that you are supposed to. We need a decent homepage, a biography of yourself, a professional looking photo of yourself, a copy of your resume, and a collection of your work/research/projects,etc. You're missing one or more pieces of the required stuff (see the note below), so do be sure you add the missing part(s) before you go using this site for real.""",
            3:"""Here we are just looking for the basics: do you have all the parts here that you are supposed to. We need a decent homepage, a biography of yourself, a professional looking photo of yourself, a copy of your resume, and a collection of your work/research/projects,etc. Unfortunately, you're missing a lot of the pieces here that we need. You really do want to go back and add the missing components because they are pretty standard for any professional e-portfolio, and your target audience will be expecting them."""
        },
        'Design' : {
            1:"""When thinking about design we are of course looking at the many principles we looked at in class - everything from color contrast to the short, simple paragraphs that are preferred for web-based writing. Does the site adhere to the tenets of simplicity, ease of use, alignment and proximity? Does it look well-made or hastily thrown together? Does it use bullet points or headers to help people navigate? Does it employ typography to help draw the reader's eye to important information? All of these elements are at play here. Overall, I think your website does a pretty good job here! It looked pretty clean to me and made good use of the 'rules' of design. I was able to navigate without too much ado, and I think that you made some smart choices about your use of color and tyopgraphy. Again, overall, this looks pretty solid. Nicely done!""",
            2:"""When thinking about design we are of course looking at the many principles we looked at in class - everything from color contrast to the short, simple paragraphs that are preferred for web-based writing. Does the site adhere to the tenets of simplicity, ease of use, alignment and proximity? Does it look well-made or hastily thrown together? Does it use bullet points or headers to help people navigate? Does it employ typography to help draw the reader's eye to important information? All of these elements are at play here. While there's always room for improvement, I think you're largely hitting the mark here. The site generally looks pretty good and adheres to most of our principles of design. There are a few spots we can fix up (see below), but overall, I think the site is generally on point as far as design is concerned. """,
            3:"""When thinking about design we are of course looking at the many principles we looked at in class - everything from color contrast to the short, simple paragraphs that are preferred for web-based writing. Does the site adhere to the tenets of simplicity, ease of use, alignment and proximity? Does it look well-made or hastily thrown together? Does it use bullet points or headers to help people navigate? Does it employ typography to help draw the reader's eye to important information? All of these elements are at play here. And yeah, the site is somewhat lacking in this department. There's a lot of design rules being broken here. Definitely go back and look at the section in our book on digital design, because there's a lot of moves here that can be made to polish this into a better looking and easier-to-naviagte page that won't push the reader away. If they don't want to visit your site because it's hard to read, then the site is not doing what it's supposed to do - our primary goal in tech writing."""
        }
    }
}

