#Add a TL;DR for students who don't want to read the whole damn thing. Something like Perfect, Almost, Missing for each category.

classes = {
    1: 'ENGL15 204'
}

classLocation = {
    1: '/media/b/Disk of Holding/School/Classes/Grades/Summer 2021/ENGL 15 204/'
}

assignments = {
    1: 'Rhetorical Analysis',
    2: 'Investigative Report',
    3: 'Productive Dialogue',
    4: 'Infographic',
    5: 'Multimedia Profile'
}

assignmentIntros = {
    'Rhetorical Analysis' : """Rhetorical Analysis: This paper is intended to do a couple things, but primarily, it's intended to introduce you to the concepts that we'll be using for the rest of the class: rhetorical appeals, the rhetotical situation, considerations of media, and most importantly, considerations of who audience and how that audience impacts the communicative act. We are looking for a paper that analyzes a rhetorical situation and judges the efficacy of the rhetor's attempts to persuade the audience. Importantly, we want to think about WHY the attempts to persuade would or would not work on the audience.""",
    'Investigative Report' : """Investigative Report: This report is less concerned with the investigation (though it's certainly a part of it) and more concerned with your ability to recognize that whatever you write needs to composed with an eye towards the audience. We describe information differently based on who we are talking to. If we talk about gravity to a five-year-old, that's different than how we would talk about gravity to a professor of physics, even if the overall information is the same. We are, of course, looking at your research, too and ensuring that you integrate your sources well and are adhering to proper MLA format.""",
    'Productive Dialogue' : """Productive Dialogue: Our primry goal here is reflected by the name change. Rather than a counter argument paper, instead we're focused more on a paper in which two people discuss a topic. You need to show me that you are capable of working with a single text for an extended period of time. Read a "target" text, identify places where you have something to respond to, lay out the context of the other side's argument, and then craft a reply that states your point of view, preferrably with research. We also want to make sure that you are using credible sources and, of course, still adhering to MLA. This process will be mirrored in your research papers throughout the rest of your college career.""",
    'Infographic' : """Instruction Set: The instruction set is one of the most ubiquitous forms of technical communication. We run into these constantly in every day life in the form of appliance manuals, repair manuals, recipes, etc. They tell the reader how to DO something. For our purposes, there are a lot of elements that come together for instruction sets that we've already talked about in previous assignments, so for this one we're focusing largely on the elements of design from our book: contrast, alignment, repetition, and proximity. In short, is the document designed so that it is usable? Can I easily follow the steps you've laid out to accomplish the task that you've designated? Are they clear, easy to follow, and written with the imperative (commanding) voice? Successfully composing an instruction set is a skill that you'll likely need at your job, whether it's composing an extensive manual or a quick memo that tells employees how to log into the company system.""",
    'Multimedia Profile' : """E-Portfolio: The e-portfolio is an opportunity for you to create a digital space for you as a professional; you are deciding how you want other professionals in your field or potential employers to view you. For the purposes of this course, we're looking for you to demonstrate a few key ideas here: professionalism, of course, but also we want you to think about what changes when we go digital. We're looking for basic design principles, including contrast, alignment and proximity, and we're also considering navigation. Is the page simple and easy to get around? Do you have the necessary parts, like the bio and headshot, a suitable homepage, and a collection of your 'stuff' you want to show off in your portfolio? Is everything presented professionally? In short, is the site well-made and clearly depict you in a professional light?"""
}

assignmentComments = {
    'Rhetorical Analysis': {
       'Audience': {
           1: """So let's start with the big question first: do you successfully identify the audience? By successful we mean, is the audience well fleshed out? Do you consider that makes them who they are - what they like, what they want , what they are afraid or what they are prejudiced against? And yeah, I think you're doing a pretty good job here. Your audience isn't just 'the person listening' or some other vague response, but is actually pretty clearly defined. They have a soul. And with that, you are significantly better poised to answer the questions about why or how the various rhetorical appeals are working on them. Looks good!""" ,
           2: """So let's start with the big question first: do you successfully identify the audience? By successful we mean, is the audience well fleshed out? Do you consider that makes them who they are - what they like, what they want , what they are afraid or what they are prejudiced against? I do think your audience gets a shape, but could be defined a little more clearly, particularly when we think about how and why the appeals are working on them. Remember, I don't just attempt to 'logos' or 'mythos' you - you may or may not respond to it. And we want to know why. The only way to do that, is to answer what it is about the audience that makes them either reject or acccept the argument of the speaker. So yeah, think about it a little bit more. What actually makes the audience who they are? """,
           3: """So let's start with the big question first: do you successfully identify the audience? By successful we mean, is the audience well fleshed out? Do you consider that makes them who they are - what they like, what they want , what they are afraid or what they are prejudiced against? Unfortunately, I think we missed the mark here. The audience is really not described basically at all aside from 'the person being spoken to.' We really want them to be defined a little more clearly, particularly when we think about how and why the appeals are working on them. Remember, I don't just attempt to 'logos' or 'mythos' you - you may or may not respond to it. And we want to know why. The only way to do that, is to answer what it is about the audience that makes them either reject or acccept the argument of the speaker. So yeah, think about it a little bit more. What actually makes the audience who they are?"""
       },
       'Rhetorical Appeals': {
           1: """Probably the next most important part of the paper is thinking about those rhetorical appeals. This is basically a vocab word check: do you correctly identify the four appeals - logos, pathos, eoths, and mythos? And yup, sure enough, you got 'em. There's not much else to say here: you identified the concepts being used correctly. Woohoo!""",
           2: """Probably the next most important part of the paper is thinking about those rhetorical appeals. This is basically a vocab word check: do you correctly identify the four appeals - logos, pathos, eoths, and mythos? And yeah, you got most of them. I think there's one or two that's a little sketchy, but you nailed some of them. Check the note below for which I think is a little off.""",
           3: """Probably the next most important part of the paper is thinking about those rhetorical appeals. This is basically a vocab word check: do you correctly identify the four appeals - logos, pathos, eoths, and mythos? But it looks like something went awry here. I'm not seeing that you understand the appeals, which is a bit of an issue. Either give them another read in the New Harbrace Guide book, or maybe schedule a meeting with me so we can talk about it?"""
       },
       'Introduction': {
           1: """We had a number of tasks we needed to accomplish with the introduction as well. We need to identify the key parts of the rhetorical situation - audience, speaker, message, and necessary background information. But of course the catch is that we want the intro to not be this monstrously huge paragraph. So to use my overly used metaphor, we're looking for a bit of a Goldilocks situation. It needs to contain all the necessary information, but not TOO much information. It's a tight rope to walk. But it's one that I think you manage to succeed at. The intro gives us what we're looking for: I understand both the rhetorical situation (which you correctly identified) and also have enough backstory for the rest of the paper to make sense. Nicely done.""",
           2: """We had a number of tasks we needed to accomplish with the introduction as well. We need to identify the key parts of the rhetorical situation - audience, speaker, message, and necessary background information. But of course the catch is that we want the intro to not be this monstrously huge paragraph. So to use my overly used metaphor, we're looking for a bit of a Goldilocks situation. It needs to contain all the necessary information, but not TOO much information. It's a tight rope to walk. And you did a pretty decent job of managing it, but I do think there's maybe just a little room for improvement here. See the note below for more details, but all things considered you gave an admirable attempt at a difficult task. So cheers to that.""",
           3: """We had a number of tasks we needed to accomplish with the introduction as well. We need to identify the key parts of the rhetorical situation - audience, speaker, message, and necessary background information. But of course the catch is that we want the intro to not be this monstrously huge paragraph. So to use my overly used metaphor, we're looking for a bit of a Goldilocks situation. It needs to contain all the necessary information, but not TOO much information. It's a tight rope to walk. Your intro went a little off the rails, honestly. We definitely to take another look at that and see how we can bring it back to where it needs to be. Remember - we need ALL the information the syllabus asks for - but nothing more. Maybe we could meet on Zoom to talk about it?"""
       }
    },
    #############################################################################################################################################
    'Investigative Report': {
        'Audience: Complexity' : {
            1:"""So when thinking about the audience and whether or not you did a good job using them as a guide for your paper, we are really thinking about a few things. One of which, is the writing itself, the complexity of your vocabulary and the actual sentences themselves. If your paper is written simply, is it because your audience would need that simplicity? Or if your paper has a higher level of complexity is it because the audience is accustomed to reading dense information? In short, do you choose a style that is appropriate to your target audience? What I'm seeing here looks pretty spot on. The diction works, the sentence complexity is appropriate and (importantly) I feel like your target audience could sit down and read this comfortably without being either confused by it's complexity nor feeling patronized by it's simplicity. In short, it hits that happy valley quite well.""",
            2:"""So when thinking about the audience and whether or not you did a good job using them as a guide for your paper, we are really thinking about a few things. One of which, is the writing itself, the complexity of your vocabulary and the actual sentences themselves. If your paper is written simply, is it because your audience would need that simplicity? Or if your paper has a higher level of complexity is it because the audience is accustomed to reading dense information? In short, do you choose a style that is appropriate to your target audience? And yeah, I think you've largely nailed it. I do spot one or two places though where you probably refine the language a little bit, though. It will probably be easiest to point out those spots on Zoom if you want to meet, but in short, I think you're largely doing a good job here and are operating at the right level of complexity with just a few hiccups here and there. So overall, I call it a win.""",
            3:"""So when thinking about the audience and whether or not you did a good job using them as a guide for your paper, we are really thinking about a few things. One of which, is the writing itself, the complexity of your vocabulary and the actual sentences themselves. If your paper is written simply, is it because your audience would need that simplicity? Or if your paper has a higher level of complexity is it because the audience is accustomed to reading dense information? In short, do you choose a style that is appropriate to your target audience? But there seems to be a disconnect here between what you wrote and who you are writing to. I get the impression that this would not go over well with your audience and the complexity (or lack thereof) of what you wrote would not sit well them. If you like, we can meet on Zoom to discuss it further, but I'd like you to think about WHO that audience is, what they are accustomed to reading, and then ask whether what you wrote meets that level of complexity."""
        },
        'Audience: Information' : {
            1:"""This is not to suggest, though, that the complexity of your sentences are the only deciding factor in whether or not your report is appropriate to the audience. Another concpet that is vitally important is what KIND of information you convey. To put it another way, do you explain what needs to be explained? A professional physicist does not need a lesson in what gravity is, but a five-year-old might. A college student knows perfectly well how to use email, but a grandmother might not. So the question becomes, are you providing the RIGHT KINDS of information for your audience? To my mind, everything here seems appropriate and on point. You provide context and further information when it's necessary and explain only what needs to be explained. I think that if your audience sat down with your paper they wouldn't skip parts of the paper because they already knew that or they wouldn't be searching for a glossary to explain something that needed more detail. Basically, you gave them the info that they would need and nothing more. """,
            2:"""This is not to suggest, though, that the complexity of your sentences are the only deciding factor in whether or not your report is appropriate to the audience. Another concpet that is vitally important is what KIND of information you convey. To put it another way, do you explain what needs to be explained? A professional physicist does not need a lesson in what gravity is, but a five-year-old might. A college student knows perfectly well how to use email, but a grandmother might not. So the question becomes, are you providing the RIGHT KINDS of information for your audience? Looks pretty good! I (of course!) was able to find a few examples, though, where you probably made some assumptions about the audience that might have been a bit much. The idea is that they should be able to read your paper they wouldn't skip parts of the paper because they already knew that or they wouldn't be searching for a glossary to explain something that needed more detail. And by and large I think you succeed except for a few spots here and there. Still, though, looks pretty good.""",
            3:"""This is not to suggest, though, that the complexity of your sentences are the only deciding factor in whether or not your report is appropriate to the audience. Another concpet that is vitally important is what KIND of information you convey. To put it another way, do you explain what needs to be explained? A professional physicist does not need a lesson in what gravity is, but a five-year-old might. A college student knows perfectly well how to use email, but a grandmother might not. So the question becomes, are you providing the RIGHT KINDS of information for your audience? I think you're making maybe too many (or not enough?) assumptions about what your audience knows or needs to know. Ideally your reader wouldn't skip parts of the paper because they already knew that or they wouldn't be searching for a glossary to explain something that needed more detail. And I'm not sure that they could, based on what you have here. Try and get into their head and think about what information they would come to your paper with and what information gaps they would likely have."""
        },
        'MLA' : {
            1:"""MLA is, well, MLA. Boooring! But, you need to know it and you need to know how to use a style guide because it will haunt you the entire time you are in college (and maybe beyond, depending on what field you settle on). Obviously for this point we're checking that you've done the MLA correctly with no errors (okay maybe I'll let you slide with one error...). And yup. Looks good. Not much else to say here aside from good job!""",
            2:"""MLA is, well, MLA. Boooring! But, you need to know it and you need to know how to use a style guide because it will haunt you the entire time you are in college (and maybe beyond, depending on what field you settle on). Obviously for this point we're checking that you've done the MLA correctly with no errors (okay maybe I'll let you slide with one error...). There's a few errors here that you should try to shore up. Definitely check out the OWL Purdue website that's on Canvas (or you can check YouTube for a tutorial - there's dozens if not hundreds of them online). If you still can't figure out what you did wrong, hit me up on Zoom and I can walk you through it.""",
            3:"""MLA is, well, MLA. Boooring! But, you need to know it and you need to know how to use a style guide because it will haunt you the entire time you are in college (and maybe beyond, depending on what field you settle on). Obviously for this point we're checking that you've done the MLA correctly with no errors (okay maybe I'll let you slide with one error...). But we have a lot more than one error here. Unfortunately your paper is pretty far from standard MLA format. Definitely check out the OWL Purdue website that's on Canvas (or you can check YouTube for a tutorial - there's dozens if not hundreds of them online). If you still can't figure out what you did wrong, hit me up on Zoom and I can walk you through it."""
        },
        'Annotated Bibliography' : {
            1:"""Just like the MLA requirement above, this is basically just a check box to make sure that you grasp the fundamentals of what makes an annotated bibliography work. We're looking for three parts: the citation, the summary, and the description of how it's useful to your paper - for each of your entries. Did you check the box? Mm hmm. Everything we need is here. Looks good and exactly like it's supposed to. Just keep in mind that this is a mini-version of the real thing. When your professors ask for an annotated bib in your future classes they will likely want a ONE PARAGRAPH summary and ONE PARAGRAPH description of why it's useful to your paper. Looks good; carry on!""",
            2:"""Just like the MLA requirement above, this is basically just a check box to make sure that you grasp the fundamentals of what makes an annotated bibliography work. We're looking for three parts: the citation, the summary, and the description of how it's useful to your paper - for each of your entries. Did you check the box? Eh, we're missing a few of the pieces here. Remember, for EACH source, we want all three parts - citation, summary, description of use. Don't forget any part! Also worth noting: this is a mini-version of the real thing. When your professors ask for an annotated bib in your future classes they will likely want a ONE PARAGRAPH summary and ONE PARAGRAPH description of why it's useful to your paper.""",
            3:"""Just like the MLA requirement above, this is basically just a check box to make sure that you grasp the fundamentals of what makes an annotated bibliography work. We're looking for three parts: the citation, the summary, and the description of how it's useful to your paper - for each of your entries. Did you check the box? Well, it's hard to say because you don't have one. :( So, yeah, I can't really tell if you did it correctly. Hopefully it's a 'Oops! I forgot!' situation and not a 'I didn't know how to do it' situation, but if it's the latter, you can go back and check the Zoom videos where we talked about it, or just meet with me on Zoom and I can walk you through it."""
        },
        'ICE Method' : {
            1:"""As you'll (hopefully) recall, one of the key ideas that we tried to stress in class is that it's generally bad to just drop a quote for the sake of quoting and then move on with your paper. Instead, we're looking for that three-step process: (I)ntroduce, (C)ite and (E)xplain the quotes you bring into the paper. While it's generally good practice to do this as often as possible (or even for EVERY quote in your paper, all I was asking for this time around was for you to show me just ONCE that you could do it successfully. And it looks like you've figured it out, which is great. Now the next step, on the next paper, is to take this idea and build upon it. Next time we want to introduce, cite, explain THEIR position, state YOUR position, and then explain YOUR position. So it'll be taking the principle you've done here and building on it a little bit. But you've got this!""",
            2:"""As you'll (hopefully) recall, one of the key ideas that we tried to stress in class is that it's generally bad to just drop a quote for the sake of quoting and then move on with your paper. Instead, we're looking for that three-step process: (I)ntroduce, (C)ite and (E)xplain the quotes you bring into the paper. While it's generally good practice to do this as often as possible (or even for EVERY quote in your paper, all I was asking for this time around was for you to show me just ONCE that you could do it successfully. You gave it a good shot, but I think that the explanation is a little bit brief. Try to connect the quote with the point you were making. The idea is that the quote should be another voice entering a conversation already happening and expressing their ideas. It is up to you to interpret that voice for the reader and explain IN DETAIL why you think that voice matters.""",
            3:"""As you'll (hopefully) recall, one of the key ideas that we tried to stress in class is that it's generally bad to just drop a quote for the sake of quoting and then move on with your paper. Instead, we're looking for that three-step process: (I)ntroduce, (C)ite and (E)xplain the quotes you bring into the paper. While it's generally good practice to do this as often as possible (or even for EVERY quote in your paper, all I was asking for this time around was for you to show me just ONCE that you could do it successfully. I'll be honest, I may have overlooked it, but I didn't spot an instance where you used the ICE method. You really want to get some practice doing this because the next paper is basically NOTHING BUT an extended version of this concept. You can check the Class Notes for more information if you need or, as ever, feel free to meet with me."""
        }
    },
    #############################################################################################################################################
    'Productive Dialogue': {
        'Step One: Identifying and explaining opposing side' : {
            1: """Perhaps the single most important concept we're looking for with this paper is that of identifying and explaining an outside source. It's vitally important that you are able to not just identify a quote that is interesting and drop it into a research paper, but that you are also able to lay out a meaningful level of context. This is the part that many students often skip and, it cannot be emphasized enough, is the part that really should NOT be skipped. It provides ethos for your argument, it shows that you understand the nuances of what you're about to argue, and it just makes the writing better. And it looks like you're working with your target text on more than just a superficial level. Your paragraphs not only identify the 'weak spot,' but also provide some analysis about the point the author is trying to make. You don't simply identify a quote and then attack it, but allow plenty of time to develop the other side and explain what you think the text is trying to do. This is perfect.""",
            2: """Perhaps the single most important concept we're looking for with this paper is that of identifying and explaining an outside source. It's vitally important that you are able to not just identify a quote that is interesting and drop it into a research paper, but that you are also able to lay out a meaningful level of context. This is the part that many students often skip and, it cannot be emphasized enough, is the part that really should NOT be skipped. It provides ethos for your argument, it shows that you understand the nuances of what you're about to argue, and it just makes the writing better. And some of the time you nail it. Some of your paragraphs are right on the money and allow time to develop the opposing side's argument before you bring your own points to the fore. But you don't always do it. Some of your paragraphs are really downplaying the opposing side and they either are simply attacking them or go off on a tangent without consideration of what the other side's argument was. This is important to avoid because it makes your paper seem like it's cherry picking it's argument or that you perhaps don't fully understand what you're arguing against. Try to identify those paragraphs where you are the primary one making a claim and the other side is downplayed, and see if you can't bring more context to the opposing sides argument.""",
            3: """Perhaps the single most important concept we're looking for with this paper is that of identifying and explaining an outside source. It's vitally important that you are able to not just identify a quote that is interesting and drop it into a research paper, but that you are also able to lay out a meaningful level of context. This is the part that many students often skip and, it cannot be emphasized enough, is the part that really should NOT be skipped. It provides ethos for your argument, it shows that you understand the nuances of what you're about to argue, and it just makes the writing better. And we've got a little bit of a red flag here. Rather than responding to the target texts' arguments, you have come to the paper with the points you want to make already ready to go. While it's good that you have points you want to make, that's not our goal with this paper. We need you to read the text and lay out the context of the argument before you start making points. I think there's definitely something we missed here - maybe we can talk about it over Zoom?"""
        },
        'Step Two: Making a claim and responding' : {
            1: """Of course a dialogue isn't a dialogue if you ONLY lay out one side - you eventually have to respond. Here we're looking for an argument that follows the point you identified and contextualized. We are looking for you to make a strong claim about the point, provide some evidence, and importantly not necessarily just beat up the other side, but thoughtfully respond to it. It looks like you're hitting this pretty well. You're not simply bringing your own arguments to the table, but are actually thinking about and responding to the point your 'opponent' made intelligently. There's enough research to back up your claims and, all in all, you're crafting a solid argument for yourself.""",
            2: """Of course a dialogue isn't a dialogue if you ONLY lay out one side - you eventually have to respond. Here we're looking for an argument that follows the point you identified and contextualized. We are looking for you to make a strong claim about the point, provide some evidence, and importantly not necessarily just beat up the other side, but thoughtfully respond to it. It looks like you're hitting this decently, but there are a few places where your claims could stand to be a little bit stronger. Remember, each paragraph should have it's own mini-thesis, the point that you are trying to make. Go back through your paragraphs and make sure that your claims are addressing the point(s) made by the target article. There's a few spots here where you could use some focus and/or bring in some precision research that addresses the target article's points.""",
            3: """Of course a dialogue isn't a dialogue if you ONLY lay out one side - you eventually have to respond. Here we're looking for an argument that follows the point you identified and contextualized. We are looking for you to make a strong claim about the point, provide some evidence, and importantly not necessarily just beat up the other side, but thoughtfully respond to it. But again, we have a bit of a problem here. Since you came to this text with your arguments all ready to go, there is no opportunity for you to even have that dialogue. The other side is missing, so it's impossible for you to respond meaningfully to their side. As you can probably guess at this point, there's definitely some work we need to do here, starting with bringing in the other side of the argument. Only then can you have a meaningful dialogue."""
        },
        'Logical Fallacies' : {
            1: """Next on our checklist is a somewhat arbitrary requirement - identifying logical fallacies - but a not unimportant one. Everyone could stand to argue a little more logically these days, and this requirement is here just to make sure you understand some of the basic mistakes people can and do make when arguing passionately for their side. So, in short, do you correctly identify at least one logical fallacy in your paper? Yep. Hooray! Well, I guess that's all I have to say about that...""",
            2: """Next on our checklist is a somewhat arbitrary requirement - identifying logical fallacies - but a not unimportant one. Everyone could stand to argue a little more logically these days, and this requirement is here just to make sure you understand some of the basic mistakes people can and do make when arguing passionately for their side. So, in short, do you correctly identify at least one logical fallacy in your paper? Well, kind of. You gave it a shot (good try!), but what you've identified isn't what's being represented by the text. Go back and check over those fallacies again, and then try it again.""",
            3: """Next on our checklist is a somewhat arbitrary requirement - identifying logical fallacies - but a not unimportant one. Everyone could stand to argue a little more logically these days, and this requirement is here just to make sure you understand some of the basic mistakes people can and do make when arguing passionately for their side. So, in short, do you correctly identify at least one logical fallacy in your paper? Nope. Well, at least I didn't see one. Give it a shot, though! There's a whole section in your book about them and besides, it's just good knowledge to have. """
        },
        'Research Credibility' : {
            1: """Finally, as for the research component, we are looking for two things: 1) 3-4 sources that are backing up your claims and 2) CREDIBLE sources, i.e., interviewing your roommmate doesn't count. When we say credible there are a lot of possible factors to account for, but perhaps the most important is that of accountability. I should be able to hold the person who made a claim accountable for their research. And it looks to me like you've done a pretty decent job here. You have the correct number of sources and they appear to be coming from sources that have a level of accountability. Looks pretty good here. """,
            2: """Finally, as for the research component, we are looking for two things: 1) 3-4 sources that are backing up your claims and 2) CREDIBLE sources, i.e., interviewing your roommmate doesn't count. When we say credible there are a lot of possible factors to account for, but perhaps the most important is that of accountability. I should be able to hold the person who made a claim accountable for their research. By and large this looks pretty good, but you're either missing a source or one of your articles is looking a little suspect. See the note below for more detail.""",
            3: """Finally, as for the research component, we are looking for two things: 1) 3-4 sources that are backing up your claims and 2) CREDIBLE sources, i.e., interviewing your roommmate doesn't count. When we say credible there are a lot of possible factors to account for, but perhaps the most important is that of accountability. I should be able to hold the person who made a claim accountable for their research. But somehow the research requirement got a little lost here. You definitely want to give this another shot with the correct amount of credible sources (3-4) to boost your grade back up."""
        }
    },
    #############################################################################################################################################
    'Infographic': {
        'Audience and Purpose' : {
            1:"""As usual, we're still concerned with the idea of audience. You've created this infographic presumably for a specific audience and for a specific purpose. The important idea is that what we've been talking about in this class so far, audince, purpose, rhetorical appeals, research, etc., can be and should be represnted visually just the same as if you were composing a proper essay. So we want to know: is this infographic designed to achieve your rhetorical purpose for a specific audience? Does the information you provide support your claim and is it appropriate for the audience? Or is it information that is tangentially related to the topic, but doesn't actually defend your argument? And yeah, I feel like you've created a document here that is accomplishing what it sets out to. There's a pretty clear thesis, and the information provided is appropriate both for the audience and for defending the point that you are trying to make. Overall, I think that infographic is pretty on point when it comes to the audience and your purpose.""", 
            2:"""As usual, we're still concerned with the idea of audience. You've created this infographic presumably for a specific audience and for a specific purpose. The important idea is that what we've been talking about in this class so far, audince, purpose, rhetorical appeals, research, etc., can be and should be represnted visually just the same as if you were composing a proper essay. So we want to know: is this infographic designed to achieve your rhetorical purpose for a specific audience? Does the information you provide support your claim and is it appropriate for the audience? Or is it information that is tangentially related to the topic, but doesn't actually defend your argument? And what you've created here works pretty well. I do think there is some room to think about what KINDS of information you are choosing to include. Some of your informational 'chunks' slip a little bit into the 'kind of relevant, but not actually defending your thesis' sort of space. Make sure that 1) you can clearly identify your purpose and then make sure to ONLY include information that does that. If some information is not directly proving your point, it either needs to be reframed or it needs to go.""",
            3:"""As usual, we're still concerned with the idea of audience. You've created this infographic presumably for a specific audience and for a specific purpose. The important idea is that what we've been talking about in this class so far, audince, purpose, rhetorical appeals, research, etc., can be and should be represnted visually just the same as if you were composing a proper essay. So we want to know: is this infographic designed to achieve your rhetorical purpose for a specific audience? Does the information you provide support your claim and is it appropriate for the audience? Or is it information that is tangentially related to the topic, but doesn't actually defend your argument? And I feel like we're slipping a little bit into the 'a collection of facts' sort of mindset. I THINK this is because there is no clear thesis here - what is it specifically that you are trying to prove. We don't simply want 'interesting facts about X', but rather an infographic composed with a purpose in mind. So be careful - just because we're no longer doing essays doesn't mean that the thesis goes away. This is an important concept because you'll be asked to do it again on the multimedia project."""
        },
        'Principles of Design' : {
            1:"""So we've made a switch here from essay to infographic, and with that switch we get some new rules - the resources and constraints of the new media, to use the lingo from the New Harbrace book. In an essay we need carefully structured paragraphs, transitions, intros and conclusions, etc., and likewise we have some rules for designing an infographic. In class we talked about color, proximity, repetition and navigation. We need two colors max that contrast and are easy to read, information that is in physical proximity to where it is being discussed, consistent formatting, and an intuitive 'flow' to the paper. So, how did you do? Colors? Check. Proximity? Looks good. Repetition of formatting? Nailed it. Intuitive navigation? On point. In short, all of the design principles seem to be playing pretty nicely here. The infographic looks pretty sharp as a result, and is easy to read and understand.""",
            2:"""So we've made a switch here from essay to infographic, and with that switch we get some new rules - the resources and constraints of the new media, to use the lingo from the New Harbrace book. In an essay we need carefully structured paragraphs, transitions, intros and conclusions, etc., and likewise we have some rules for designing an infographic. In class we talked about color, proximity, repetition and navigation. We need two colors max that contrast and are easy to read, information that is in physical proximity to where it is being discussed, consistent formatting, and an intuitive 'flow' to the paper. So, how did you do? The infographic generally looks pretty good, but I do have a few spots that catch my eye - some rules that you've broken. The question, of course, is whether you broke those rules because you simply didn't know and did it wrong, or if you broke those rules because of reasons. I'll be looking for some explanation in the cover letter about some of your design decisions. You can see more specifics below.""",
            3:"""So we've made a switch here from essay to infographic, and with that switch we get some new rules - the resources and constraints of the new media, to use the lingo from the New Harbrace book. In an essay we need carefully structured paragraphs, transitions, intros and conclusions, etc., and likewise we have some rules for designing an infographic. In class we talked about color, proximity, repetition and navigation. We need two colors max that contrast and are easy to read, information that is in physical proximity to where it is being discussed, consistent formatting, and an intuitive 'flow' to the paper. So, how did you do? But somehow, some way we've design this and were either unaware of those principles of design or else we simply didn't understand them. There's a lot here to nitpick. I'll check the cover letter to see if you can explain some of the design choices you've made here, but what I'm seeing at the moment is violating a fair few of the core design principles we talked about in class, which is a little troubling."""
        },
        'Data Visualization (1 = Have it, 2 = Do not)' : {
            1:"""Another required component of this assignment was the data visualization, i.e., you needed to include a chart, graph, word cloud, timeline, etc., that allows the reader to visually comprehend some form of information. The idea here is directly tied to the project itself. In a standard essay we tell the reader information using words. A data visualization can convey the same information, but more quickly - a picture is worth a thousand words as they say. The inclusion of the data visualization is a microcosm of the infographic as a whole. Can we take information which would conventionally be expressed in an essay format and reconfigure it visually? And it looks like you've got the idea. You have some data, some information that the reader needs to comprehend that has been incorporated into the project visually. It checks the box that we're looking for and is useful for understanding something that would be otherwise fairly complex at a glance. Nicely done.""",
            2:"""Another required component of this assignment was the data visualization, i.e., you needed to include a chart, graph, word cloud, timeline, etc., that allows the reader to visually comprehend some form of information. The idea here is directly tied to the project itself. In a standard essay we tell the reader information using words. A data visualization can convey the same information, but more quickly - a picture is worth a thousand words as they say. The inclusion of the data visualization is a microcosm of the infographic as a whole. Can we take information which would conventionally be expressed in an essay format and reconfigure it visually? But it looks like you may have forgotten about this requirement! I'm not seeing the data visualization here. Remember, we're looking for some way to convey information via picture or graph or chart. The idea is that we can convey complex information and even contextualize that information via image, which saves on words and time spent analyzing the topic. See if you can't find an appropriate visualization to lend credence to your argument."""
        },
        'Cover Letter' : {
            1:"""Switching gears a bit, the cover letter was an important component to this assignment for a few reasons. 1) Because I don't expect you to be a graphical designer, the cover letter is intended to allow you to explain what you were attempting to do, even if you weren't always successful in the execution. 2) Also, the cover letter allows you a moment to reflect on where you were intentionally breaking rules or making design choices that might leave me scratching my head. 3) Finally, the letter also allows you a space to reflect on the creation of the project in a more meta fashion, thinking about the process of converting the concepts that so far have been reserved for essays into a more visual format. Your cover letter pretty much fit the bill here. Any lingering questions I had about your project were addressed here, you explained your mindset and design decisions, and were able to generally reflect on your writing as a whole. This is an underrated skill: thinking about your learning is something that is often viewed as busy work, but studies show that thinking about your thinking improves your, uh, thinking. But yeah, you've done a nice job here. Looks good.""",
            2:"""Switching gears a bit, the cover letter was an important component to this assignment for a few reasons. 1) Because I don't expect you to be a graphical designer, the cover letter is intended to allow you to explain what you were attempting to do, even if you weren't always successful in the execution. 2) Also, the cover letter allows you a moment to reflect on where you were intentionally breaking rules or making design choices that might leave me scratching my head. 3) Finally, the letter also allows you a space to reflect on the creation of the project in a more meta fashion, thinking about the process of converting the concepts that so far have been reserved for essays into a more visual format. Yours looks pretty good! That said, I can't let you go without a little griping. I do think that there were some questions that I had about your project that I didn't see fully addressed here in the cover letter. Maybe you could explain a little more clearly (or at all) why you made certain choices in the creation of your infographic. Again, check out the additional comment at the bottom here for more specifics on what I think we're missing. But overall, I do think the cover letter it's doing it's job pretty well and is a good reflection on your thinking process.""",
            3:"""Switching gears a bit, the cover letter was an important component to this assignment for a few reasons. 1) Because I don't expect you to be a graphical designer, the cover letter is intended to allow you to explain what you were attempting to do, even if you weren't always successful in the execution. 2) Also, the cover letter allows you a moment to reflect on where you were intentionally breaking rules or making design choices that might leave me scratching my head. 3) Finally, the letter also allows you a space to reflect on the creation of the project in a more meta fashion, thinking about the process of converting the concepts that so far have been reserved for essays into a more visual format. Annnd... oh no! Yours is missing! I hope that you just forgot to upload it and didn't skip it entirely! It is worth a huge portion of the grade for this assignment, so you definitely want to get that to me, if you're able. You want to reflect on the things I listed and create a 2-3 page (double spaced) document detailing your thoughts as you created your project."""
        },
        'Scholarly Source (1 = Have it, 2 = Do not)' : {
            1:"""Finally, the last little check box that we're looking at is your research. For this particular assignment, it was required that you have at least one scholarly source. And you did. So that's good. Your source looks good to me, and we can now say that you've jumped through the initial ENGL 15 hoop of gaining experience searching through the library/Google scholar for good, scholarly sources. Hooray!""",
            2:"""Finally, the last little check box that we're looking at is your research. For this particular assignment, it was required that you have at least one scholarly source. And I don't think we've quite hit the mark here. Remember, scholarly = published in a peer reviewed journal or in a book by a reputable publishing company. You want to use Lion Search's tool for narrowing your sources down to peer reviewed and scholarly in order to find these types of sources, or alternatively you can use Google Scholar, which can help find the right stuff. Let me know if you have questions about how to do this!"""
        }
    },
    #############################################################################################################################################
    #e-Portfolio
    'Multimedia Profile': {
        'Audience/Professionalism' : {
            1:"""Of course our biggest concern here lies in the overall presentation of you as a professional and how your audience, i.e., people in your specific field or potential employers, will view you and your web page. Looking at the page broadly, we want to ask if it comes across as professional in all of the elements: design, content, navigation, etc. Is your writing and your information relevant and in line with your potential occupation? And yeah, everything here looks pretty sharp. The information you choose to include is relevant, the writing itself maintains a formal tone, and the design is not overly garish but instead maintains a level of simplicity and elegance. Overall, I think it looks pretty solid.""",
            2:"""Of course our biggest concern here lies in the overall presentation of you as a professional and how your audience, i.e., people in your specific field or potential employers, will view you and your web page. Looking at the page broadly, we want to ask if it comes across as professional in all of the elements: design, content, navigation, etc. Is your writing and your information relevant and in line with your potential occupation? I do think there's a little room for improvement here. Some of the choices you've made don't 100% exude a level of tight professionalism. Remember that audience and what they are going to be interested in and want to see. They want a simple-to-navigate page that looks sharp, they want information about you and your professional interests (and nothing else), and they expect a level of formality here. See if you can't reign in some of your design choices to up your professionalism game to 100%.""",
            3:"""Of course our biggest concern here lies in the overall presentation of you as a professional and how your audience, i.e., people in your specific field or potential employers, will view you and your web page. Looking at the page broadly, we want to ask if it comes across as professional in all of the elements: design, content, navigation, etc. Is your writing and your information relevant and in line with your potential occupation? And this page is not quite hitting the mark here. It's... unprofessional, for lack of a better word. Remember, this is not a Facebook or Instagram page. We want to design a site that only shows off the serious, career-minded side of you. See if you can't make some design choices here that will give the audience what they are looking for: They want a simple-to-navigate page that looks sharp, they want information about you and your professional interests (and nothing else), and they expect a level of formality here."""
        },
        'Complete Content' : {
            1:"""Here we are just looking for the basics: do you have all the parts here that you are supposed to. We need a decent homepage, a biography of yourself, a professional looking photo of yourself, a copy of your resume, and a collection of your work/research/projects,etc. And yep. You've got everything you need. Looks good.""",
            2:"""Here we are just looking for the basics: do you have all the parts here that you are supposed to. We need a decent homepage, a biography of yourself, a professional looking photo of yourself, a copy of your resume, and a collection of your work/research/projects,etc. You're missing one or more pieces of the required stuff (see the note below), so do be sure you add the missing part(s) before you go using this site for real.""",
            3:"""Here we are just looking for the basics: do you have all the parts here that you are supposed to. We need a decent homepage, a biography of yourself, a professional looking photo of yourself, a copy of your resume, and a collection of your work/research/projects,etc. Unfortunately, you're missing a lot of the pieces here that we need. You really do want to go back and add the missing components because they are pretty standard for any professional e-portfolio, and your target audience will be expecting them."""
        },
        'Design' : {
            1:"""When thinking about design we are of course looking at the many principles we looked at in class - everything from color contrast to the short, simple paragraphs that are preferred for web-based writing. Does the site adhere to the tenets of simplicity, ease of use, alignment and proximity? Does it look well-made or hastily thrown together? Does it use bullet points or headers to help people navigate? Does it employ typography to help draw the reader's eye to important information? All of these elements are at play here. Overall, I think your website does a pretty good job here! It looked pretty clean to me and made good use of the 'rules' of design. I was able to navigate without too much ado, and I think that you made some smart choices about your use of color and tyopgraphy. Again, overall, this looks pretty solid. Nicely done!""",
            2:"""When thinking about design we are of course looking at the many principles we looked at in class - everything from color contrast to the short, simple paragraphs that are preferred for web-based writing. Does the site adhere to the tenets of simplicity, ease of use, alignment and proximity? Does it look well-made or hastily thrown together? Does it use bullet points or headers to help people navigate? Does it employ typography to help draw the reader's eye to important information? All of these elements are at play here. While there's always room for improvement, I think you're largely hitting the mark here. The site generally looks pretty good and adheres to most of our principles of design. There are a few spots we can fix up (see below), but overall, I think the site is generally on point as far as design is concerned. """,
            3:"""When thinking about design we are of course looking at the many principles we looked at in class - everything from color contrast to the short, simple paragraphs that are preferred for web-based writing. Does the site adhere to the tenets of simplicity, ease of use, alignment and proximity? Does it look well-made or hastily thrown together? Does it use bullet points or headers to help people navigate? Does it employ typography to help draw the reader's eye to important information? All of these elements are at play here. And yeah, the site is somewhat lacking in this department. There's a lot of design rules being broken here. Definitely go back and look at the section in our book on digital design, because there's a lot of moves here that can be made to polish this into a better looking and easier-to-naviagte page that won't push the reader away. If they don't want to visit your site because it's hard to read, then the site is not doing what it's supposed to do - our primary goal in tech writing."""
        }
    }
}

